- name: restorecon django
  command: "restorecon -ivr {{ app.value.django.user.home }}/django"
  become: True
  become_user: root

- name: restart uwsgi
  systemd:
    daemon_reload: yes
    name: "{{ app.value.django.user.user }}-django-uwsgi-{{ app.key }}.service"
    state: restarted
  become: True
  become_user: root
